tasks:
  Python:
    extensions: [py]
    highlighter: python
    command: python {path}{file}{ext}
  Compile:
    extensions: [cpp, h]
    highlighter: cpp
    command: g++ -std=c++20 -pthread -I./include src/*.cpp src/data/*.cpp src/interpreter/*.cpp blombly.cpp -o blombly -O2 -fdiagnostics-color
  Blombly:
    extensions: [bb, bbvm]
    highlighter: rust
    command: cmd /C "blombly.exe" {path}{file}{ext}
  Push:
    extensions: [gitignore]
    highlighter: txt
    command: cmd /C git add . && git commit -m "{commit message}" && git push
  Pull:
    extensions: [gitignore]
    highlighter: txt
    command: cmd /C git pull
  
