!!utils.Tasks
tasks:
  Blombly:
    command: '{cmd}./blombly {path}{file}.bb'
    extensions: [.bb]
    highlighter: text/rust
  View:
    command: '{cmd} {open} "{path}{file}.html"'
    extensions: [.html]
    highlighter: text/html
