name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            build-script: .\vcpkg\bootstrap-vcpkg.bat
            cmake-command: |
              cmake -B ./build
              cmake --build ./build --config Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ${{ matrix.build-script }}

    - name: Install dependencies
      run: |
        ./vcpkg/vcpkg install crow civetweb zlib --triplet=${{ matrix.triplet }}

    - name: Configure and build
      run: |
        ${{ matrix.cmake-command }}

    - name: Package executable for Windows
      run: |
        mkdir -p release
        cp ./*.exe release/ || echo "No executables found"
        cp ./*.dll release/ || echo "No DLLs found"
        cp -r libs/ release/ || echo "No libs directory found"
        # Use PowerShell's Compress-Archive for zipping files on Windows
        powershell Compress-Archive -Path release/* -DestinationPath windows_release.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: windows_release.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Windows build artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: .

      - name: List downloaded files (Debugging step)
        run: ls -al

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: windows_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
